---
- hosts: all
  tasks:
    - name: User exist and are in the correct groups
      user:
        name: "{{ item['name'] }}"
        state: present
        groups: "{{ item['groups'] }}"
      loop:
        - name: jane
          groups: wheel
        - name: joe
          groups: root

